### ISSUE TITLE
Notes to self: Priest Scroll Component

### ISSUE THREAD

**Issue by Grammarsalad** [UnearthedArcana/Faiths_and_Powers#161]
Before creation, create an "exclude" list of all existing scrolls already in game of the form: 

"%scroll_res%" => "%scroll_res%"

No need to do this in the middle of the code. 

Gha, this means rewriting most of the code again...

**Comment by CaptOcto** [comment]
Hi there is this note related to struggling to install F&P and SCS?

At SCS I got:

ERROR: Failure("You are trying to edit %WIZARD_ACID_STORM_SCROLL%.ITM, which does not exist in the game")
NOT INSTALLED DUE TO ERRORS Initialise AI components (required for all tactical and AI components)

My research suggests this is because F&P created an Acid Storm spell but no corresponding scroll. Is there a way for me to fix this to be able to install your mod which looks really amazing?

Cheers

**Comment by Grammarsalad** [comment]
@CaptOcto 
I'm doing a component for F&P that will create missing priest scrolls. The code can also be used to create missing wizard scrolls as well. 

Also, we should--I thought we already had--move away from creating mage scrolls for this priest mod. 

What version are you using? Did the updated version still have this issue?

**Comment by Grammarsalad** [comment]
this is actually already done. WIll close shortly but waiting for response from Capt

**Comment by CaptOcto** [comment]
Hi thanks!
I think it was my poor mod order, once I put IWDification before F&Ps it
installed okay.

Cheers,
Aram

**Comment by Grammarsalad** [comment]
@CaptOcto 
Thanks, that's still good to know.
